rorcode/counter/config/routes.rb
Rails.application.routes.draw do
  root 'site#index'
  get 'site/index'
  get 'site/increment', as: :increment
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

rorcode/counter/app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def increment
    @counter = params[:counter].to_i + 1
  end
end

rorcode/counter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AndroidTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

rorcode/counter/app/views/site/increment.html.erb
<turbo-frame id='counter'>
    <div class="mt-4">
        Counter: <%= @counter %>
    </div>
    <div class="mt-4">
        <%= link_to 'Increment', increment_path(counter: @counter),
        class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
    </div>
    
</turbo-frame>

rorcode/counter/app/views/site/index.html.erb
<%# <h1>Site#index</h1>

<h1 class="text-3xl font-bold underline">
    Hello world!
</h1>

<h1 class="font-bold text-4xl text-blue-500">Public#index</h1> %>

<%= turbo_frame_tag 'counter', src: increment_path %>